#Datos de la evidencia
#Tue Sep 08 09:45:43 GMT-05:00 2026
description=Contiene las 5 infograf\u00EDas, que son\:\r\n. Actores de un Proyecto Web\r\n. Herramientas de Gesti\u00F3n de un Proyecto Web\r\n. Organizaci\u00F3n del Tipo de Trabajo\r\n. Roles y Responsabilidades\r\n. Tipos de Proyecto Web
title=Infografias
